version: "3"
services:
  # El "Cerebro" que coordina todo
  selenium-hub:
    image: selenium/hub:4.16.1
    container_name: selenium-hub
    ports:
      - "4444:4444"

  # El "MÃºsculo" para Chrome (puedes escalar este servicio)
  chrome:
    image: selenium/node-chrome:4.16.1
    shm_size: 2gb  # Importante para evitar que Chrome colapse
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443