version: '3.8'

services:
  # Nodo especializado para el SRI (Score más alto requerido)
  sri_bot:
    image: selenium/standalone-chrome:latest
    container_name: bot_sri_session
    ports:
      - "4444:4444" # API Selenium
      - "7900:7900" # Interfaz Visual (VNC)
    volumes:
      - ./sessions/sri:/home/seluser/.config/google-chrome
    shm_size: 2gb

  # Nodo para Superintendencia de Compañías
  supercias_bot:
    image: selenium/standalone-chrome:latest
    container_name: bot_supercias_session 
    ports:
      - "4445:4444" # API Selenium
      - "7901:7900" # Interfaz Visual (VNC)
    volumes:
      - ./sessions/supercias:/home/seluser/.config/google-chrome
    shm_size: 2gb

  # Nodo para Función Judicial
  judicial_bot:
    image: selenium/standalone-chrome:latest
    container_name: bot_judicial_session
    ports:
      - "4446:4444" # API Selenium
      - "7902:7900" # Interfaz Visual (VNC)
    volumes:
      - ./sessions/judicial:/home/seluser/.config/google-chrome
      - ./descargas_judiciales:/tmp/files/downloads
    shm_size: 2gb